apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-config
  namespace: "{{ .Values.pack.namespace }}"
data:
  PORT: "{{ .Values.config.port }}"
  GREETING: "{{ .Values.config.greeting }}"
  ENVIRONMENT: "{{ .Values.config.environment }}"
